### PR TITLE
Move Pyro Capabilities into PySP

### PR DESCRIPTION
**Pull request by mrmundt**
## Summary/Motivation:
In order to separate PyUtilib from Pyomo, we need to move the `pyutilib.pyro` functionality. The general agreement was to move it into PySP.

## Changes proposed in this PR:
- Add `pyro` capability
- Add console scripts
- Fix GHA Codecov upload driver bug

### Legal Acknowledgement

By contributing to this software project, I have read the [Pyomo contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
@jsiirola @ghackebeil @whart222 - FYI, I can't remove pyro from Pyomo until this PR is reviewed/merged.

**Comment by ghackebeil** [comment]
Running through some local testing of this now.

**Comment by ghackebeil** [comment]
Started the following:
 - `pyomo_ns -n localhost` (installed with pysp)
 - `dispatch_srvr -n localhost` (installed with pyutilib)

Verified that the following all work as expected:
 - running a parallel pysp algorithm. E.g.,
    - `scenariotreeserver --pyro-host=localhost` (start up N of these, installed with pysp)
    - `python -m pysp.solvers.benders --scenario-tree-manager=pyro --pyro-host=localhost ...`
 - running a serial pysp algorithm with pyro solver manager. E.g.,
   - `pyro_mip_server --pyro-host=localhost` (start up N of these, installed with pysp)
   - `python -m pysp.solvers.benders --subproblem-solver-manager=pyro --subproblem-solver-manager-pyro-host=localhost...`
 - running a simple example with `SolverManagerFactory("pyro")` with a separate `pyro_mip_server --pyro-host=localhost` proc
 ```
import pyomo.kernel as pmo
import pyomo.environ

# this triggers the SolverManagerFactory registration                                                                                     
import pysp.pyro                                                                                                      

model = pmo.block()
model.x = pmo.variable()
model.p = pmo.parameter(-1)
model.o = pmo.objective(model.x)
model.c = pmo.constraint(model.x >= model.p)

manager = pyomo.environ.SolverManagerFactory("pyro")
results = manager.solve(model, solver="glpk")
print(results)
```
 - The included `python sudoku_run_pyro.py` with N separate `python sudoku_pyro_worker.py` procs running

**Comment by ghackebeil** [comment]
The one rfc I have is that the sudoku example is missing the main model definition file `sudoku.py`, so perhaps that should be included. It's also probably a good idea to move the `pysp/pysp/pyro/examples` directory out to the top-level examples directory (e.g., `pysp/examples/pyro_sudoku`)

**Comment by ghackebeil** [comment]
Actually, I'm fine with whatever you all decide regarding the pyro examples directory. Not super important.

**Review by ghackebeil — APPROVED** [review]

**Comment by mrmundt** [comment]
> The one rfc I have is that the sudoku example is missing the main model definition file `sudoku.py`, so perhaps that should be included. It's also probably a good idea to move the `pysp/pysp/pyro/examples` directory out to the top-level examples directory (e.g., `pysp/examples/pyro_sudoku`)

Good call. I moved the files into the main `examples` folder (but just under `pyro`) and grabbed the rest of the sudoku files.

**Review by ghackebeil — APPROVED** [review]
Good catch

**Pull request merged**
